export const TYPES = {
  Logger: Symbol.for('Logger'),
  TwitterClient: Symbol.for('TwitterClient'),
  RettiwtSearchBuilder: Symbol.for('RettiwtSearchBuilder'),
  SearchStrategy: Symbol.for('SearchStrategy'),
  SearchCacheManager: Symbol.for('SearchCacheManager'),
  MetricsManager: Symbol.for('MetricsManager'),
  RateLimitedQueue: Symbol.for('RateLimitedQueue'),
  ConfigManager: Symbol.for('ConfigManager'),
  CircuitBreaker: Symbol.for('CircuitBreaker'),
  ErrorHandler: Symbol.for('ErrorHandler'),
  TwitterNotifier: Symbol.for('TwitterNotifier'),
  TelegramBot: Symbol.for('TelegramBot'),
  TopicManager: Symbol.for('TopicManager'),
  MessageStorage: Symbol.for('MessageStorage'),
  Environment: Symbol.for('Environment'),
  Storage: Symbol.for('Storage'),
  TweetFormatter: Symbol.for('TweetFormatter'),
  DateValidator: Symbol.for('DateValidator'),
  TweetProcessor: Symbol.for('TweetProcessor'),
  RettiwtKeyManager: Symbol.for('RettiwtKeyManager'),
  SearchConfig: Symbol.for('SearchConfig'),
  BasePath: Symbol.for('BasePath'),
  // Add new types
  TelegramMessageQueue: Symbol.for('TelegramMessageQueue'),
  TelegramQueueConfig: Symbol.for('TelegramQueueConfig'),
  FilterPipeline: Symbol.for('FilterPipeline'),
  TelegramMessageSender: Symbol.for('TelegramMessageSender')
};