name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: npm run build
        
      - name: Create config file
        run: |
          echo "${{ secrets.CONFIG_JSON }}" > config.json
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop existing service if running
            pm2 stop tgnoti || true
            
            # Create/clear deployment directory
            mkdir -p /root/tgnoti
            cd /root/tgnoti
            
            # Remove old files except config and data
            find . -not -name 'config.json' -not -name 'messages.db*' -not -name '.' -not -name '..' -delete
            
            # Create necessary directories
            mkdir -p dist
            
      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/,package.json,package-lock.json,config.json"
          target: "/root/tgnoti"
          
      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/tgnoti
            npm ci --production
            pm2 start dist/index.js --name tgnoti